### ISSUE TITLE
Compile failed with @angular/compiler-cli@7.2.12

### ISSUE THREAD

**Issue by QimatLuo** [ionic-team/ionic-v3#1009]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**
```
> ionic-app-scripts build --prod
[11:44:31]  ionic-app-scripts 3.2.3 
[11:44:31]  build prod started ...
[11:44:31]  clean started ...
[11:44:31]  clean finished in 1 ms
[11:44:31]  copy started ...
[11:44:31]  deeplinks started ...
[11:44:31]  deeplinks finished in 25 ms
[11:44:31]  ngc started ...
[11:44:36]  typescript: src/page-nav/page-nav.ts, line: 52 
            Argument of type
            'import("/Users/qimatluo/test/node_modules/ionic-angular/transitions/transition-controller").TransitionController'                                                                                    
            is not assignable to parameter of type
            'import("/Users/qimatluo/test/node_modules/ionic-angular/umd/transitions/transition-controller").TransitionController'.                                                                               
            Types of property 'plt' are incompatible. Type
            'import("/Users/qimatluo/test/node_modules/ionic-angular/platform/platform").Platform' is not assignable to                                                                                           
            type 'import("/Users/qimatluo/test/node_modules/ionic-angular/umd/platform/platform").Platform'. Types have                                                                                           
            separate declarations of a private property '_win'.

      L51:  ) {
      L52:  nt, app, config, plt, elementRef, zone, renderer, cfr, gestureCtrl, transCtrl, linker, domCtrl, errHandler);                                                                                          

[11:44:36]  ionic-app-script task: "build" 
[11:44:36]  Error: The Angular AoT build failed. See the issues above 
Error: The Angular AoT build failed. See the issues above
    at /Users/qimatluo/test/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:232:55
    at step (/Users/qimatluo/test/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:32:23)
    at Object.next (/Users/qimatluo/test/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:13:53)
    at fulfilled (/Users/qimatluo/test/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:4:58)
[ERROR] An error occurred while running subprocess ionic-app-scripts.

        ionic-app-scripts build --prod exited with exit code 1.

        Re-running this command with the --verbose flag may provide more information.
```

**Expected behavior:**
Build success

**Steps to reproduce:**

1. create a ionic 3 project
1. fix npm audit warnings (the keypoint is the @angular/compiler-cli@7.2.12)
1. make a component extend Nav
1. ionic build --prod

**Related code:**

here is the example component code
```
import {
  forwardRef,
  Component,
  ComponentFactoryResolver,
  ErrorHandler,
  ElementRef,
  NgZone,
  Optional,
  Renderer,
  ViewEncapsulation,
} from '@angular/core';
import {
  App,
  Config,
  DeepLinker,
  DomController,
  GestureController,
  Nav,
  NavController,
  Platform,
  RootNode,
  ViewController,
} from 'ionic-angular';
import { TransitionController } from 'ionic-angular/transitions/transition-controller';

@Component({
  selector: 'page-nav',
  template:
    '<div #viewport nav-viewport></div>' +
    '<div class="nav-decor"></div>',
  encapsulation: ViewEncapsulation.None,
  providers: [{ provide: RootNode, useExisting: forwardRef(() => PageNav) }]
})
export class PageNav extends Nav {

  constructor(
    @Optional() viewCtrl: ViewController,
    @Optional() parent: NavController,
    app: App,
    config: Config,
    plt: Platform,
    elementRef: ElementRef,
    zone: NgZone,
    renderer: Renderer,
    cfr: ComponentFactoryResolver,
    gestureCtrl: GestureController,
    transCtrl: TransitionController,
    @Optional() linker: DeepLinker,
    domCtrl: DomController,
    errHandler: ErrorHandler,
  ) {
    super(viewCtrl, parent, app, config, plt, elementRef, zone, renderer, cfr, gestureCtrl, transCtrl, linker, domCtrl, errHandler);
  }
}
```

**Other information:**
if not upgrade @angular/compiler-cli will be fine.
Due to the npm audit warning, I upgrade the library cause this issue.
Should I keep audit warnning to not upgrade the library?

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic:

   ionic (Ionic CLI)  : 4.12.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.3
   @ionic/app-scripts : 3.2.3

System:

   NodeJS : v11.13.0 (/usr/local/Cellar/node/11.13.0/bin/node)
   npm    : 6.7.0
   OS     : macOS Mojave
```

**Comment by longgt** [comment]
#1034
https://forum.ionicframework.com/t/angular-6-ionic-3/129773/8
