### ISSUE TITLE
Angular 8 removes deprecated import of DOCUMENT from @angular/platform-browser

### ISSUE THREAD

**Issue by MarekBodinger** [ionic-team/ionic-v3#1034]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**
When compiling using Webpack:
![image](https://user-images.githubusercontent.com/11184728/58562716-14295080-822a-11e9-8aae-a438c9be5062.png)

When running the app, it doesn't start:
```
compiler.js:21544 Uncaught Error: Can't resolve all parameters for setupPlatform: (?, [object Object], [object Object]).
    at syntaxError (compiler.js:2687) [<root>]
    at CompileMetadataResolver._getDependenciesMetadata (compiler.js:21355) [<root>]
    at CompileMetadataResolver._getFactoryMetadata (compiler.js:21255) [<root>]
    at CompileMetadataResolver.getProviderMetadata (compiler.js:21487) [<root>]
    at eval (compiler.js:21417) [<root>]
    at Array.forEach (<anonymous>) [<root>]
    at CompileMetadataResolver._getProvidersMetadata (compiler.js:21377) [<root>]
    at eval (compiler.js:21000) [<root>]
    at Array.forEach (<anonymous>) [<root>]
    at CompileMetadataResolver.getNgModuleMetadata (compiler.js:20991) [<root>]
    at JitCompiler._loadModules (compiler.js:27143) [<root>]
    at JitCompiler._compileModuleAndComponents (compiler.js:27124) [<root>]
    at JitCompiler.compileModuleAsync (compiler.js:27084) [<root>]
    at CompilerImpl.compileModuleAsync (platform-browser-dynamic.js:158) [<root>]
    at compileNgModuleFactory__PRE_R3__ (core.js:25059) [<root>]
    at PlatformRef.bootstrapModule (core.js:25268) [<root>]
    at eval (mobile.main.ts:7) [<root>]
    at Object../mobile_app/mobile.main.ts (mobile.bundle.js:450) [<root>]
    at __webpack_require__ (mobile.bundle.js:84) [<root>]
    at eval (webpack:///multi_(webpack)-dev-server/client?:2:18) [<root>]
    at Object.10 (mobile.bundle.js:774) [<root>]
    at __webpack_require__ (mobile.bundle.js:84) [<root>]
    at checkDeferredModules (mobile.bundle.js:46) [<root>]
    at static/mobile.bundle.js:218:18 [<root>]
    at static/mobile.bundle.js:221:10 [<root>]
```

**Expected behavior:**
The application compiles and runs without errors.

**Steps to reproduce:**
Use `ionic-angular` with Angular version 8+.

**Related code:**
Angular 8 removes deprecated `DOCUMENT` import from `@angular/platform-browser` and replaces it with import from `@angular/common`. https://github.com/angular/angular/issues/28117

When replacing imports with the correct path, the app compiles correctly.

**Comment by longgt** [comment]
Ionic 3 only supports for Angular 5.
If you need to support Anguar 6, try it https://github.com/ionic-team/ionic-v3/pull/812
For Angular 7, 8, please switch to Ionic 4.

**Comment by mbalty** [comment]
I get the same error when trying to run and I am using Ionic 5 with angular 8. I would appreciate the help. Thanks

**Comment by MarekBodinger** [comment]
We've found a dirty workaround. It's possible to replace the value of `DOCUMENT` before the app is initialized in `IonicModule` definition.

Firstly, import correct `DOCUMENT`.
```import { DOCUMENT } from '@angular/common';```

Secondly, create function that patches `IonicModule` definition.
```
function getFixedIonicModuleImport() {
    const ionicModuleForRoot = IonicModule.forRoot(MobileAppComponent);
    const providerForPlatform = ionicModuleForRoot.providers.find(
        provider => (provider as FactoryProvider).provide === Platform,
    ) as FactoryProvider;
    if (providerForPlatform.deps[0] === undefined) {
        providerForPlatform.deps[0] = DOCUMENT;
    }

    return ionicModuleForRoot;
}
```

Finally, use `getFixedIonicModuleImport()`.

**Comment by mbalty** [comment]
How and where exactly do I call `getFixedIonicModuleImport() `. If I replace `    IonicModule.forRoot(MyApp),`, it breaks when I run ionic serve:
`Error: Could not find IonicModule.forRoot call in "imports"`. Thank you!

**Comment by MarekBodinger** [comment]
We use, custom compilation script, therefore we don't use `ionic serve`.

https://github.com/ionic-team/ionic-app-scripts/blob/master/src/deep-linking/util.ts#L280
There is a check for `IonicModule.forRoot` in Ionic.

I am not sure, but another possibility would be to monkey patch the function to return the patched variant.
