### ISSUE TITLE
excludeFromRecents="true" causes app to be killed on Android 9 - Target SDK 28

### ISSUE THREAD

**Issue by 8bhsolutions** [ionic-team/ionic-v3#1073]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**
On Android 9 (sdk 28), when app has the setting android:excludeFromRecents="true" set in the activity, when you opened YouTube (or other apps), the cordova app is killed.

**Expected behavior:**
The app should not be impacted

**Steps to reproduce:**
1. Start the app. (NOTE - The start date on the Home Tab shows when the instance of the app is started. It will remain static for the duration of the app instance.)
2. Once app is started. Go to app launcher
3. Launch Calculator app (or another app)
4. Go back to the app - via app launcher (since the app is excluded from recent list). 
5. Notice the app starts a new instance (because app start date is different).

**Related code:**

https://github.com/8bhsolutions/test-excludeFromRecents

**Other information:**
Reproduced on both real device and emulator

Real device - Samsung S9+ running latest Android 9
Emulator (Genymotion v3.0.3) - Samsung S9 - Android 9 - stock image

No errors/exceptions in logcat for why the CordovaActivity is killed (line 2 below)

```
10-19 00:42:00.380: W/libprocessgroup(486): kill(-2215, 9) failed: No such process
10-19 00:42:00.388: D/CordovaActivity(2560): CordovaActivity.onDestroy()
10-19 00:42:00.391: D/CordovaWebViewImpl(2560): >>> loadUrl(about:blank)
10-19 00:42:00.392: W/cr_AwContents(2560): WebView.destroy() called while WebView is still attached to window.
10-19 00:42:00.399: W/Finsky(1820): [2] com.google.android.finsky.analytics.az.a(40): Null bundle, which breaks event chain!. Creating a new logging context.
10-19 00:42:00.406: I/Zygote(317): Process 1516 exited due to signal (9)
10-19 00:42:00.417: I/Zygote(317): Process 2215 exited due to signal (9)
10-19 00:42:00.424: W/libprocessgroup(486): kill(-2215, 9) failed: No such process
10-19 00:42:00.424: I/libprocessgroup(486): Successfully killed process cgroup uid 10071 pid 2215 in 44ms
10-19 00:42:00.424: W/libprocessgroup(486): kill(-1516, 9) failed: No such process
10-19 00:42:00.424: I/libprocessgroup(486): Successfully killed process cgroup uid 10023 pid 1516 in 0ms
10-19 00:42:00.439: I/ActivityManager(486): START u0 {act=android.intent.action.MAIN cmp=com.android.vending/com.google.android.finsky.unauthenticated.UnauthenticatedMainActivity (has extras)} from uid 10079
10-19 00:42:00.486: E/chromium(2560): [ERROR:gl_context_virtual.cc(39)] Trying to make virtual context current without decoder.
10-19 00:42:00.546: W/cr_AwContents(2560): Application attempted to call on a destroyed WebView
10-19 00:42:00.546: W/cr_AwContents(2560): java.lang.Throwable
10-19 00:42:00.546: W/cr_AwContents(2560): 	at org.chromium.android_webview.AwContents.isDestroyed(AwContents.java:351)
10-19 00:42:00.546: W/cr_AwContents(2560): 	at org.chromium.android_webview.AwContents.isDestroyedOrNoOperation(AwContents.java:323)
10-19 00:42:00.546: W/cr_AwContents(2560): 	at org.chromium.android_webview.AwContents.getTitle(AwContents.java:585)
10-19 00:42:00.546: W/cr_AwContents(2560): 	at org.chromium.android_webview.AwWebContentsDelegateAdapter.loadingStateChanged(AwWebContentsDelegateAdapter.java:132)
10-19 00:42:00.546: W/cr_AwContents(2560): 	at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
10-19 00:42:00.546: W/cr_AwContents(2560): 	at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:9)
10-19 00:42:00.546: W/cr_AwContents(2560): 	at android.os.Handler.dispatchMessage(Handler.java:106)
10-19 00:42:00.546: W/cr_AwContents(2560): 	at android.os.Looper.loop(Looper.java:193)
10-19 00:42:00.546: W/cr_AwContents(2560): 	at android.app.ActivityThread.main(ActivityThread.java:6680)
10-19 00:42:00.546: W/cr_AwContents(2560): 	at java.lang.reflect.Method.invoke(Native Method)
10-19 00:42:00.546: W/cr_AwContents(2560): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
10-19 00:42:00.546: W/cr_AwContents(2560): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
10-19 00:42:00.564: W/SurfaceFlinger(370): Attempting to destroy on removed layer: AppWindowToken{5fd14b3 token=Token{aac2222 ActivityRecord{c4853ed u0 io.ionic.starter/.MainActivity t48}}}#0
10-19 00:42:00.603: I/cr_ChildProcessService(2724): Destroying ChildProcessService pid=2724
10-19 00:42:00.605: I/ActivityManager(486): Killing 2724:com.android.webview:sandboxed_process1/u0a4i1 (adj 0): isolated not needed

```

-----

The bug is more obvious if you include https://github.com/katzer/cordova-plugin-background-mode plugin to the source, because the notification (used for the foreground service) associated with the app is removed when the app is killed.

I purposely choose to not include the background mode plugin in the sample project to isolate the issue.

-----

**Environment**
Ionic:

   Ionic CLI          : 5.2.3
   Ionic Framework    : ionic-angular 3.9.5
   @ionic/app-scripts : 3.2.2

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.2, (and 4 other plugins)

Utility:

   cordova-res : 0.8.0
   native-run  : 0.2.8

System:

   Android SDK Tools : 26.1.1 
   NodeJS            : v10.16.0
   npm               : 6.9.0
   OS                : Windows 10

**Comment by 8bhsolutions** [comment]
#https://github.com/apache/cordova-android/issues/851#issuecomment-544199490
